name=TinyPortal
version=1.0.0
author=OrkaLxrd
maintainer=OrkaLxrd
sentence=Simple captive portal for ESP32 and ESP8266
paragraph=TinyPortal provides DNS hijack and redirect for captive portal functionality without interfering with your existing WebServer.
category=Communication
url=https://github.com/OrkaLxrd/TinyPortal
architectures=esp8266,esp32
